- CHANGELOG.md
- ClientApp/package.json
- ClientApp/src/components/Footer.js
- ClientApp/src/components/Navigation.js
- ClientApp/src/components/dashboard/Dashboard.js
- ClientApp/src/components/misc/Getter.js
- ClientApp/src/components/misc/Record.js
- ClientApp/src/components/tests/EDRSRoundtripConsuming.js
- ClientApp/src/components/tests/EDRSRoundtripProducing.js
- ClientApp/src/components/tests/FHIRConsuming.js
- ClientApp/src/components/tests/FHIRProducing.js
- ClientApp/src/components/tools/FHIRCreator.js
- ClientApp/src/index.css
- ClientApp/src/index.js
- ClientApp/yarn.lock
- Controllers/EndpointsController.cs
- Migrations/20190213145807_InitialCreate.Designer.cs
- Migrations/20190213145807_InitialCreate.cs
- Migrations/RecordContextModelSnapshot.cs
- Models/Endpoint.cs
- Models/Record.cs
* Enabled ability to "POST" records into Canary
* FHIR Validator now shows all issues found in a record, instead of just the first
* Improvements made to record importing speed
* Tweaked navigation dropdowns to be more responsive
* Various dependency updates
> Improvements for version 0.10.0

- canary.tests/MessagesControllerTests.cs
- canary/ClientApp/src/components/misc/info/Property.js
- canary/Models/Connectathon.cs
- canary/Models/DeathRecordFaker.cs
- canary/Models/Message.cs
- canary/canary.csproj
- canary/connectathon_files/1_janet_page_cancer_R4.xml
- canary/connectathon_files/2_madelyn_patel_opiod_R4.xml
- canary/connectathon_files/3_vivienne_wright_pregnant_R4.xml
- canary/connectathon_files/4_javier_perez_accident_full_R4.xml
- canary/connectathon_files/5_javier_perez_accident_partial_R4.xml
Most recent changes for R4 connectathon files
> R4 connectathon files

- canary/ClientApp/src/components/dashboard/ConnectathonDashboard.js
This should fix the failing step "Build Self-Contained Windows Executable"
> Fix missing === which was raising an error on build

- CHANGELOG.md
- canary/ClientApp/package-lock.json
- canary/ClientApp/src/components/tests/FHIRIJEValidatorProducing.js
- canary/ClientApp/src/index.js
- canary/canary.csproj
Also fix a few npm warnings and fix `canary/ClientApp/src/components/tests/FHIRIJEValidatorProducing.js` to not have warnings that are currently causing the build to fail.
> Release version v3.0.1

- canary/Models/Connectathon.cs
Updated the values in the connectathon test cases to match the test case definition spreadsheet.
> Correct Military Service connectathon test case values (addresses NVSS-263)

- canary/Models/Connectathon.cs
> Updated SSN of connectathon record to reflect test case update

- canary/Models/Connectathon.cs
This pull request addresses NVSS-267
> Updated residence address of connectathon record to match test case

- canary/Models/Connectathon.cs
The ethnicity for test 3 in Canary had not been updated to "Salvadoran" to match the provided test case.
> Update test 3 ethnicity to match test case

- canary/Models/Connectathon.cs
I looked through the test case spreadsheet for any fields that still needed updating in canary Connectathon.cs I only found one field that needed an update, registration date for test case 1, Janet Page.
> fix-date-tast-case-1

- canary/ClientApp/package-lock.json
- canary/Controllers/RecordsController.cs
- canary/Models/DeathRecordFaker.cs
- canary/Models/Record.cs
- canary/Models/Test.cs
- canary/canary.csproj
This pull request
1. Removes references to some death record properties that no longer exist (UsualOccupationEnd, BirthSex, InjuryLocationDescription)
2. Updates library dependencies to support the .NET 3.1 to 6.0 upgrade
3. Uses a much better approach for selecting the correct custom attributes
4. Updates project JS dependencies (limiting to hypothetically non-breaking changes)
> Library updates

- canary/ClientApp/package.json
- canary/ClientApp/src/index.js
- canary/Models/DeathRecordFaker.cs
- canary/canary.csproj
changed library version v4.0.0-preview6 and made one small fix
> Update canary version

- canary/ClientApp/package.json
- canary/ClientApp/src/index.js
change version number to v4.0.0-preview3
> Correct version number

- canary/canary.csproj
bump library version to include fix for mother, father, spouse active field
> Update library version

- canary/Models/Test.cs
Makes the comparison of coded values and cause of death coding case sensitive
> Make coded values case sensitive

- CHANGELOG.md
- README.md
- canary/ClientApp/src/index.js
- canary/canary.csproj
Updated the VRDR .NET library dependency for the project to use [V4.0.0-preview18](https://github.com/nightingaleproject/vrdr-dotnet/releases/tag/v4.0.0-preview18)
> Updated version to 4.0.0-preview9

- canary/ClientApp/src/components/misc/Record.js
- Default selection to JSON record type when viewing messages
- Arrange JSON record type to be the first menu item
> UI: Default JSON record type

- canary.sln
- canary/canary.csproj
> chore: restore original solution and project file

- Directory.Build.props
- canary/ClientApp/src/index.js
- canary/canary.csproj
Once merged, need to make a release to publish to https://canary.ctex-inc.com.
> chore: update VRDR .NET dependency

- .devcontainer/devcontainer.json
Add Docker-in-Docker feature so images can be built inside the dev container. See https://github.com/devcontainers/features/tree/main/src/docker-in-docker for additional details.
> ci: add docker-in-docker feature

- canary/ClientApp/src/error.js
- canary/Filter/ExceptionHandlingFilter.cs
- canary/Startup.cs
Added a global error handling class and hooked to controllers to report errors to client UI
> feat: better error handling
